
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt -r test-requirements.txt
  - pip install codecov
  - pip install --no-deps .
  - python setup.py install
script:
  - PYTHONPATH=.:$PYTHONPATH python tests/__main__.py
after_success:
  - PYTHONPATH=.:$PYTHONPATH coverage run --omit=*test* tests/__main__.py
  - codecov
